# team abbreviation list
teams = ['ARI', 'ATL', 'BAL', 'BOS', 'CHC', 'CHW', 'CIN', 'CLE', 'COL', 'DET', 'HOU', 'KCR', 'LAA', 'LAD', 'MIA',
         'MIL', 'MIN', 'NYM', 'NYY', 'OAK', 'PHI', 'PIT', 'SDP', 'SEA', 'SFG', 'STL', 'TBR', 'TEX', 'TOR', 'WSN']

# batting stats verbose names to abbreviations
stats_from_verbose = {
    'Number of Batters': '#Bat',
    'Average Age of Batters': 'BatAge',
    'Runs Per Game': 'R/G',
    # 'Games': 'G',
    'Plate Appearances': 'PA',
    'At Bats': 'AB',
    'Runs': 'R_h',
    'Hits': 'H_h',
    'Doubles': '2B',
    'Triples': '3B',
    'Home Runs': 'HR_h',
    'Runs Batted In': 'RBI',
    'Stolen Bases': 'SB',
    'Caught Stealing': 'CS',
    'Walks': 'BB_h',
    'Strikeouts': 'SO_h',
    'Batting Average': 'BA',
    'On-base Percentage': 'OBP',
    'Slugging': 'SLG',
    'On-base Plus Slugging': 'OPS+',
    'Total Bases': 'TB',
    'Grounded Into Double Plays': 'GIDP',
    'Hit By Pitches': 'HBP_h',
    'Shutouts': 'SH',
    'Sacrifice Flies': 'SF',
    'Intentional Walks': 'IBB_h',
    'Left On-base': 'LOB_h',
    'Number of Pitchers': '#P',
    'Average Age of Pitchers': 'PAge',
    'Runs Allowed Per Game': 'RA/G',
    'Wins': 'W',
    'Losses': 'L',
    'Win-Loss Percentage': 'W-L%',
    'Earned Run Average': 'ERA',
    'Games Started': 'GS',
    'Games Finished': 'GF',
    'Complete Games': 'CG',
    'Team Shutouts': 'tSho',
    'Complete Game Shutouts': 'cSho',
    'Saves': 'SV',
    'Innings Pitched': 'IP',
    'Hits Allowed': 'H_p',
    'Runs Allowed': 'R_p',
    'Earned Runs': 'ER',
    'Walks Allowed': 'BB_p',
    'Intentional Walks Allowed': 'IBB_p',
    'Strikeouts Thrown': 'SO_p',
    'Hit By Pitches Thrown': 'HBP_p',
    'Home Runs Allowed': 'HR_p',
    'Balks': 'BK',
    'Wild Pitches': 'WP',
    'Batters Faced': 'BF',
    'Earned Run Average Plus': 'ERA+',
    'Fielding Independent Pitching': 'FIP',
    'Walks and Hits Per Inning Pitched': 'WHIP',
    'Hits Per 9 Innings': 'H9',
    'Home Runs Per 9 Innings': 'HR9',
    'Walks Per 9 Innings': 'BB9',
    'Strikeouts Per 9 Innings': 'SO9',
    'Strikeout-to-Walk Ratio': 'SO/W',
    'Left On-base Allowed': 'LOB_p',
    'Reached On Error': 'ROE',
    'Catcher Interference': 'XI',
    'Run Scoring Percentage': 'RS%',
    'Stolen Base Opportunities': 'SBO',
    'Stolen Base Percentage': 'SB%',
    'Steals of 2nd Base': 'SB2',
    'Steals of 3rd Base': 'SB3',
    'Caught Stealing 2nd Base': 'CS2',
    'Caught Stealing 3rd Base': 'CS3',
    'Steals of Home': 'SBH',
    'Caught Stealing Home': 'CSH',
    'Pickoffs': 'PO',
    'Pickoff Caught Stealing': 'PCS',
    'Outs on Base': 'OOB',
    'Outs on Base at 1st': 'OOB1',
    'Outs on Base at 2nd': 'OOB2',
    'Outs on Base at 3rd': 'OOB3',
    'Outs on Base at Home': 'OOBHm',
    'Bases Taken': 'BT',
    'Extra Bases Taken Percentage': 'XBT%',
    'On 1st, When Single Hit': '1stS',
    'On 1st, When Single Hit and Reaches 2nd': '1stS2',
    'On 1st, When Single Hit and Reaches 3rd or Scores': '1stS3',
    'On 1st, When Double Hit': '1stD',
    'On 1st, When Double Hit and Reaches 3rd': '1stD3',
    'On 1st, When Double Hit and Scores': '1stDH',
    'On 2nd, When Single Hit': '2ndS',
    'On 2nd, When Single Hit and Reaches 3rd': '2ndS3',
    'On 2nd, When Single Hit and Scores': '2ndSH',
}

# batting stats abbreviations to verbose names
# reverse pairs of dict with verbose name keys
stats_to_verbose = {v: k for (k, v) in stats_from_verbose.items()}