branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: eb-baseball-flask
  branch: master
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: MLB_SportsRef_Graph
  sc: git
  workspace_type: Application
